name: CI/CD for Spring Boot

on:
  push:
    branches:
      - "master"
      - "develop"
      - "feature-IOMS-**"  # Matches all feature branches (e.g., feature/IOMS-1007)
  pull_request:
    branches:
      - "master"
      - "develop"
      - "feature-IOMS-**"  # Matches pull requests to these branches
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read  # Default permissions
  pull-requests: read  # Required for SonarCloud PR decoration

jobs:
  build-and-test:
    name: Build and Test with Maven
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Validate commit message format
      - name: Validate commit message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          # Regex to match <ticket-ID>: Meaningful message
          if ! echo "$COMMIT_MSG" | grep -qE "^[A-Za-z0-9\-]+-[0-9]+: .+"; then
            echo "Error: Invalid commit message format."
            echo "Commit message must follow the format: <ticket-ID>: Meaningful message"
            exit 1  # Fail the build if the commit message doesn't match
          fi

      # Step 3: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"  # Set your project's JDK version (e.g., 8, 11, 17)

      # Step 4: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 5: Build and test with Maven (Ensure target/classes is generated)
      - name: Build and test
        run: mvn clean install  # Using install ensures that the classes are generated
        env:
          MAVEN_OPTS: "-Xmx1024m -XX:MaxMetaspaceSize=256m"  # Updated memory settings for Java 17
